AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: cmda
    Description: A Lambda stack to support the cmda command line tool
    Author: LambCI
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README-SAR.md
    Labels: ['lambda', 'filesystem']
    HomePageUrl: https://github.com/lambci/cmda
    SemanticVersion: 0.9.4
    SourceCodeUrl: https://github.com/lambci/cmda/tree/v0.9.4
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: VPC Configuration (optional)
        Parameters:
          - VpcSubnetIds
          - VpcSecurityGroupIds
    ParameterLabels:
      VpcSubnetIds:
        default: Subnet IDs
      VpcSecurityGroupIds:
        default: Security Group ID(s)

Parameters:
  VpcSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: VPC Subnet IDs (typically you only want private subnets)
    Default: ''
  VpcSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: VPC Security Group ID(s) (typically you only want one)
    Default: ''

Conditions:
  AddVpcConfig:
    Fn::And:
      - Fn::Not: [Fn::Equals: ['', Fn::Join: ['', !Ref VpcSubnetIds]]]
      - Fn::Not: [Fn::Equals: ['', Fn::Join: ['', !Ref VpcSecurityGroupIds]]]

Resources:

  CmdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      CodeUri: lambda/dist
      Handler: index.handler
      MemorySize: 3008
      Timeout: 900
      ReservedConcurrentExecutions: 1
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref CmdaBucket
      Environment:
        Variables:
          CMDA_BUCKET: !Ref CmdaBucket
      VpcConfig:
        Fn::If:
          - AddVpcConfig
          - SubnetIds: !Ref VpcSubnetIds
            SecurityGroupIds: !Ref VpcSecurityGroupIds
          - !Ref AWS::NoValue

  CmdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 1
            Status: Enabled

Outputs:
  FunctionName:
    Description: The name of the cmda Lambda function
    Value: !Ref CmdaFunction
